package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TAd;
import com.landasoft.players.pojo.TAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int countByExample(TAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int deleteByExample(TAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int insert(TAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int insertSelective(TAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    List<TAd> selectByExample(TAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    TAd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") TAd record, @Param("example") TAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int updateByExample(@Param("record") TAd record, @Param("example") TAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int updateByPrimaryKeySelective(TAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad
     *
     * @mbggenerated Fri Feb 21 20:05:06 CST 2020
     */
    int updateByPrimaryKey(TAd record);
}