package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TCarousel;
import com.landasoft.players.pojo.TCarouselExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int countByExample(TCarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int deleteByExample(TCarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int insert(TCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int insertSelective(TCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    List<TCarousel> selectByExample(TCarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    TCarousel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") TCarousel record, @Param("example") TCarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int updateByExample(@Param("record") TCarousel record, @Param("example") TCarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int updateByPrimaryKeySelective(TCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    int updateByPrimaryKey(TCarousel record);
}