package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TLog;
import com.landasoft.players.pojo.TLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int countByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int deleteByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int insert(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int insertSelective(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    List<TLog> selectByExample(TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    TLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") TLog record, @Param("example") TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int updateByExample(@Param("record") TLog record, @Param("example") TLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int updateByPrimaryKeySelective(TLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    int updateByPrimaryKey(TLog record);
}