package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TMediaInfo;
import com.landasoft.players.pojo.TMediaInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMediaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int countByExample(TMediaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int deleteByExample(TMediaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int insert(TMediaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int insertSelective(TMediaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    List<TMediaInfo> selectByExample(TMediaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    TMediaInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") TMediaInfo record, @Param("example") TMediaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int updateByExample(@Param("record") TMediaInfo record, @Param("example") TMediaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int updateByPrimaryKeySelective(TMediaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_info
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    int updateByPrimaryKey(TMediaInfo record);
}