package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TVisitNum;
import com.landasoft.players.pojo.TVisitNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVisitNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int countByExample(TVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int deleteByExample(TVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int insert(TVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int insertSelective(TVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    List<TVisitNum> selectByExample(TVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    TVisitNum selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") TVisitNum record, @Param("example") TVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int updateByExample(@Param("record") TVisitNum record, @Param("example") TVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int updateByPrimaryKeySelective(TVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    int updateByPrimaryKey(TVisitNum record);
}