package com.landasoft.players.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCarouselExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public TCarouselExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCarouselNameIsNull() {
            addCriterion("carousel_name is null");
            return (Criteria) this;
        }

        public Criteria andCarouselNameIsNotNull() {
            addCriterion("carousel_name is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselNameEqualTo(String value) {
            addCriterion("carousel_name =", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameNotEqualTo(String value) {
            addCriterion("carousel_name <>", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameGreaterThan(String value) {
            addCriterion("carousel_name >", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameGreaterThanOrEqualTo(String value) {
            addCriterion("carousel_name >=", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameLessThan(String value) {
            addCriterion("carousel_name <", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameLessThanOrEqualTo(String value) {
            addCriterion("carousel_name <=", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameLike(String value) {
            addCriterion("carousel_name like", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameNotLike(String value) {
            addCriterion("carousel_name not like", value, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameIn(List<String> values) {
            addCriterion("carousel_name in", values, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameNotIn(List<String> values) {
            addCriterion("carousel_name not in", values, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameBetween(String value1, String value2) {
            addCriterion("carousel_name between", value1, value2, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselNameNotBetween(String value1, String value2) {
            addCriterion("carousel_name not between", value1, value2, "carouselName");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkIsNull() {
            addCriterion("carousel_link is null");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkIsNotNull() {
            addCriterion("carousel_link is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkEqualTo(String value) {
            addCriterion("carousel_link =", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkNotEqualTo(String value) {
            addCriterion("carousel_link <>", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkGreaterThan(String value) {
            addCriterion("carousel_link >", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkGreaterThanOrEqualTo(String value) {
            addCriterion("carousel_link >=", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkLessThan(String value) {
            addCriterion("carousel_link <", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkLessThanOrEqualTo(String value) {
            addCriterion("carousel_link <=", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkLike(String value) {
            addCriterion("carousel_link like", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkNotLike(String value) {
            addCriterion("carousel_link not like", value, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkIn(List<String> values) {
            addCriterion("carousel_link in", values, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkNotIn(List<String> values) {
            addCriterion("carousel_link not in", values, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkBetween(String value1, String value2) {
            addCriterion("carousel_link between", value1, value2, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselLinkNotBetween(String value1, String value2) {
            addCriterion("carousel_link not between", value1, value2, "carouselLink");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirIsNull() {
            addCriterion("carousel_image_dir is null");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirIsNotNull() {
            addCriterion("carousel_image_dir is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirEqualTo(String value) {
            addCriterion("carousel_image_dir =", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirNotEqualTo(String value) {
            addCriterion("carousel_image_dir <>", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirGreaterThan(String value) {
            addCriterion("carousel_image_dir >", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirGreaterThanOrEqualTo(String value) {
            addCriterion("carousel_image_dir >=", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirLessThan(String value) {
            addCriterion("carousel_image_dir <", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirLessThanOrEqualTo(String value) {
            addCriterion("carousel_image_dir <=", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirLike(String value) {
            addCriterion("carousel_image_dir like", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirNotLike(String value) {
            addCriterion("carousel_image_dir not like", value, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirIn(List<String> values) {
            addCriterion("carousel_image_dir in", values, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirNotIn(List<String> values) {
            addCriterion("carousel_image_dir not in", values, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirBetween(String value1, String value2) {
            addCriterion("carousel_image_dir between", value1, value2, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselImageDirNotBetween(String value1, String value2) {
            addCriterion("carousel_image_dir not between", value1, value2, "carouselImageDir");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceIsNull() {
            addCriterion("carousel_price is null");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceIsNotNull() {
            addCriterion("carousel_price is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceEqualTo(Short value) {
            addCriterion("carousel_price =", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceNotEqualTo(Short value) {
            addCriterion("carousel_price <>", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceGreaterThan(Short value) {
            addCriterion("carousel_price >", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceGreaterThanOrEqualTo(Short value) {
            addCriterion("carousel_price >=", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceLessThan(Short value) {
            addCriterion("carousel_price <", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceLessThanOrEqualTo(Short value) {
            addCriterion("carousel_price <=", value, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceIn(List<Short> values) {
            addCriterion("carousel_price in", values, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceNotIn(List<Short> values) {
            addCriterion("carousel_price not in", values, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceBetween(Short value1, Short value2) {
            addCriterion("carousel_price between", value1, value2, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselPriceNotBetween(Short value1, Short value2) {
            addCriterion("carousel_price not between", value1, value2, "carouselPrice");
            return (Criteria) this;
        }

        public Criteria andCarouselSortIsNull() {
            addCriterion("carousel_sort is null");
            return (Criteria) this;
        }

        public Criteria andCarouselSortIsNotNull() {
            addCriterion("carousel_sort is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselSortEqualTo(Byte value) {
            addCriterion("carousel_sort =", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortNotEqualTo(Byte value) {
            addCriterion("carousel_sort <>", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortGreaterThan(Byte value) {
            addCriterion("carousel_sort >", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortGreaterThanOrEqualTo(Byte value) {
            addCriterion("carousel_sort >=", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortLessThan(Byte value) {
            addCriterion("carousel_sort <", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortLessThanOrEqualTo(Byte value) {
            addCriterion("carousel_sort <=", value, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortIn(List<Byte> values) {
            addCriterion("carousel_sort in", values, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortNotIn(List<Byte> values) {
            addCriterion("carousel_sort not in", values, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortBetween(Byte value1, Byte value2) {
            addCriterion("carousel_sort between", value1, value2, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselSortNotBetween(Byte value1, Byte value2) {
            addCriterion("carousel_sort not between", value1, value2, "carouselSort");
            return (Criteria) this;
        }

        public Criteria andCarouselStateIsNull() {
            addCriterion("carousel_state is null");
            return (Criteria) this;
        }

        public Criteria andCarouselStateIsNotNull() {
            addCriterion("carousel_state is not null");
            return (Criteria) this;
        }

        public Criteria andCarouselStateEqualTo(Byte value) {
            addCriterion("carousel_state =", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateNotEqualTo(Byte value) {
            addCriterion("carousel_state <>", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateGreaterThan(Byte value) {
            addCriterion("carousel_state >", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("carousel_state >=", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateLessThan(Byte value) {
            addCriterion("carousel_state <", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateLessThanOrEqualTo(Byte value) {
            addCriterion("carousel_state <=", value, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateIn(List<Byte> values) {
            addCriterion("carousel_state in", values, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateNotIn(List<Byte> values) {
            addCriterion("carousel_state not in", values, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateBetween(Byte value1, Byte value2) {
            addCriterion("carousel_state between", value1, value2, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCarouselStateNotBetween(Byte value1, Byte value2) {
            addCriterion("carousel_state not between", value1, value2, "carouselState");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_carousel
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 19 16:40:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_carousel
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}