package com.landasoft.players.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TCarousel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.id
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_name
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private String carouselName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_link
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private String carouselLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_image_dir
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private String carouselImageDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_price
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private Short carouselPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_sort
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private Byte carouselSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.carousel_state
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    private Byte carouselState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.created
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.updated
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.id
     *
     * @return the value of t_carousel.id
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.id
     *
     * @param id the value for t_carousel.id
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_name
     *
     * @return the value of t_carousel.carousel_name
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public String getCarouselName() {
        return carouselName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_name
     *
     * @param carouselName the value for t_carousel.carousel_name
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselName(String carouselName) {
        this.carouselName = carouselName == null ? null : carouselName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_link
     *
     * @return the value of t_carousel.carousel_link
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public String getCarouselLink() {
        return carouselLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_link
     *
     * @param carouselLink the value for t_carousel.carousel_link
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselLink(String carouselLink) {
        this.carouselLink = carouselLink == null ? null : carouselLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_image_dir
     *
     * @return the value of t_carousel.carousel_image_dir
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public String getCarouselImageDir() {
        return carouselImageDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_image_dir
     *
     * @param carouselImageDir the value for t_carousel.carousel_image_dir
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselImageDir(String carouselImageDir) {
        this.carouselImageDir = carouselImageDir == null ? null : carouselImageDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_price
     *
     * @return the value of t_carousel.carousel_price
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Short getCarouselPrice() {
        return carouselPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_price
     *
     * @param carouselPrice the value for t_carousel.carousel_price
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselPrice(Short carouselPrice) {
        this.carouselPrice = carouselPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_sort
     *
     * @return the value of t_carousel.carousel_sort
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Byte getCarouselSort() {
        return carouselSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_sort
     *
     * @param carouselSort the value for t_carousel.carousel_sort
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselSort(Byte carouselSort) {
        this.carouselSort = carouselSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.carousel_state
     *
     * @return the value of t_carousel.carousel_state
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Byte getCarouselState() {
        return carouselState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.carousel_state
     *
     * @param carouselState the value for t_carousel.carousel_state
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCarouselState(Byte carouselState) {
        this.carouselState = carouselState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.created
     *
     * @return the value of t_carousel.created
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.created
     *
     * @param created the value for t_carousel.created
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.updated
     *
     * @return the value of t_carousel.updated
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.updated
     *
     * @param updated the value for t_carousel.updated
     *
     * @mbggenerated Wed Feb 19 16:40:24 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}