package com.landasoft.players.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.id
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.operator
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.oper_event
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    private String operEvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.created
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.id
     *
     * @return the value of t_log.id
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.id
     *
     * @param id the value for t_log.id
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.operator
     *
     * @return the value of t_log.operator
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.operator
     *
     * @param operator the value for t_log.operator
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.oper_event
     *
     * @return the value of t_log.oper_event
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public String getOperEvent() {
        return operEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.oper_event
     *
     * @param operEvent the value for t_log.oper_event
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public void setOperEvent(String operEvent) {
        this.operEvent = operEvent == null ? null : operEvent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.created
     *
     * @return the value of t_log.created
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.created
     *
     * @param created the value for t_log.created
     *
     * @mbggenerated Thu Feb 20 10:41:41 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}