package com.landasoft.players.pojo;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TMediaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.id
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.media_name
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private String mediaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.media_size
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private Integer mediaSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.media_image_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private String mediaImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.media_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private String mediaUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.created
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.updated
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_media_info.state
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.id
     *
     * @return the value of t_media_info.id
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.id
     *
     * @param id the value for t_media_info.id
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.media_name
     *
     * @return the value of t_media_info.media_name
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public String getMediaName() {
        return mediaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.media_name
     *
     * @param mediaName the value for t_media_info.media_name
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName == null ? null : mediaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.media_size
     *
     * @return the value of t_media_info.media_size
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public Integer getMediaSize() {
        return mediaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.media_size
     *
     * @param mediaSize the value for t_media_info.media_size
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setMediaSize(Integer mediaSize) {
        this.mediaSize = mediaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.media_image_url
     *
     * @return the value of t_media_info.media_image_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public String getMediaImageUrl() {
        return mediaImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.media_image_url
     *
     * @param mediaImageUrl the value for t_media_info.media_image_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setMediaImageUrl(String mediaImageUrl) {
        this.mediaImageUrl = mediaImageUrl == null ? null : mediaImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.media_url
     *
     * @return the value of t_media_info.media_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public String getMediaUrl() {
        return mediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.media_url
     *
     * @param mediaUrl the value for t_media_info.media_url
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl == null ? null : mediaUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.created
     *
     * @return the value of t_media_info.created
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.created
     *
     * @param created the value for t_media_info.created
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.updated
     *
     * @return the value of t_media_info.updated
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.updated
     *
     * @param updated the value for t_media_info.updated
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_media_info.state
     *
     * @return the value of t_media_info.state
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_media_info.state
     *
     * @param state the value for t_media_info.state
     *
     * @mbggenerated Thu Feb 13 10:21:08 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }
}