package com.landasoft.players.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TVisitNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_num.id
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_num.visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    private Short visitNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_num.created
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_num.updated
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_num.id
     *
     * @return the value of t_visit_num.id
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_num.id
     *
     * @param id the value for t_visit_num.id
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_num.visit_num
     *
     * @return the value of t_visit_num.visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public Short getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_num.visit_num
     *
     * @param visitNum the value for t_visit_num.visit_num
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public void setVisitNum(Short visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_num.created
     *
     * @return the value of t_visit_num.created
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_num.created
     *
     * @param created the value for t_visit_num.created
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_num.updated
     *
     * @return the value of t_visit_num.updated
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_num.updated
     *
     * @param updated the value for t_visit_num.updated
     *
     * @mbggenerated Sat Feb 22 14:49:53 CST 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}