package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TAdminUser;
import com.landasoft.players.pojo.TAdminUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int countByExample(TAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int deleteByExample(TAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int insert(TAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int insertSelective(TAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    List<TAdminUser> selectByExample(TAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    TAdminUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") TAdminUser record, @Param("example") TAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByExample(@Param("record") TAdminUser record, @Param("example") TAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByPrimaryKeySelective(TAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_user
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByPrimaryKey(TAdminUser record);
}