package com.landasoft.players.mapper;

import com.landasoft.players.pojo.TMediaVisitNum;
import com.landasoft.players.pojo.TMediaVisitNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMediaVisitNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int countByExample(TMediaVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int deleteByExample(TMediaVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int insert(TMediaVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int insertSelective(TMediaVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    List<TMediaVisitNum> selectByExample(TMediaVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    TMediaVisitNum selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") TMediaVisitNum record, @Param("example") TMediaVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByExample(@Param("record") TMediaVisitNum record, @Param("example") TMediaVisitNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByPrimaryKeySelective(TMediaVisitNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_media_visit_num
     *
     * @mbggenerated Thu Feb 13 11:40:21 CST 2020
     */
    int updateByPrimaryKey(TMediaVisitNum record);
}